name: eslint-check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        name: Eslint project check
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm lint