name: ESLint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Eslint checker
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run eslint .